name: safeguard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geocoding: ^4.0.0
  location: ^8.0.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  contacts_service_plus: ^0.0.2
  url_launcher: ^6.3.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
