// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsPeTTHDjuo6xODJ7BCfXYfMCwnL47udQ',
    appId: '1:475996546501:web:a174f3bf0db895ae2917ac',
    messagingSenderId: '475996546501',
    projectId: 'safeguard-ad3a1',
    authDomain: 'safeguard-ad3a1.firebaseapp.com',
    storageBucket: 'safeguard-ad3a1.firebasestorage.app',
    measurementId: 'G-FRCW075GR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVwtAd1iCU25cmhjrLMW-oHLicDP-Ymck',
    appId: '1:475996546501:android:287cfd1f7131e8be2917ac',
    messagingSenderId: '475996546501',
    projectId: 'safeguard-ad3a1',
    storageBucket: 'safeguard-ad3a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdWNBcFFGquyehiwImoO5WyuMhvD5Q-Dg',
    appId: '1:475996546501:ios:aed82863d68a0fdb2917ac',
    messagingSenderId: '475996546501',
    projectId: 'safeguard-ad3a1',
    storageBucket: 'safeguard-ad3a1.firebasestorage.app',
    iosBundleId: 'com.example.safeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdWNBcFFGquyehiwImoO5WyuMhvD5Q-Dg',
    appId: '1:475996546501:ios:aed82863d68a0fdb2917ac',
    messagingSenderId: '475996546501',
    projectId: 'safeguard-ad3a1',
    storageBucket: 'safeguard-ad3a1.firebasestorage.app',
    iosBundleId: 'com.example.safeguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsPeTTHDjuo6xODJ7BCfXYfMCwnL47udQ',
    appId: '1:475996546501:web:061ff5c770e8b2292917ac',
    messagingSenderId: '475996546501',
    projectId: 'safeguard-ad3a1',
    authDomain: 'safeguard-ad3a1.firebaseapp.com',
    storageBucket: 'safeguard-ad3a1.firebasestorage.app',
    measurementId: 'G-KHM7DQZQW6',
  );

}